name = "alyssawelt"
compatibility_date = "2026-08-20"
pages_build_output_dir = "./public"

[vars]
CF_ACCOUNT_ID = "191b6a6ae524ccdd29763caa18587808"
TO_EMAIL = "alyassa@alyssawelt.com"
FROM_EMAIL = "noreply@alyssawelt.com"
